### PR TITLE
add testing framework, .gitignore

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
coverage : https://acdl.mit.edu/csi/job/designspaceviz_PullRequest/9/buildnode=reynolds,optimizer=mosek/cobertura/

**Review by priyappillai — APPROVED** [review]
:+1: should probably add more details to test cases rather than simply making sure they don't throw an error, but works for now

**Pull request merged**
